# Generated by Django 5.2.17 on 2026-10-03 08:32

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Specimen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "specimen_code",
                    models.CharField(
                        editable=False, max_length=96, unique=True, verbose_name="標本番号"
                    ),
                ),
                (
                    "detail_uuid",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="詳細用識別子",
                    ),
                ),
                (
                    "identification_text",
                    models.CharField(blank=True, max_length=500, verbose_name="同定情報"),
                ),
                (
                    "acquisition_method",
                    models.CharField(
                        choices=[
                            ("collected", "採集"),
                            ("purchased", "購入"),
                            ("donated", "寄贈"),
                            ("other", "その他"),
                        ],
                        max_length=16,
                    ),
                ),
                ("collected_on", models.DateField(blank=True, null=True, verbose_name="採集日")),
                (
                    "collected_place",
                    models.CharField(blank=True, max_length=500, verbose_name="採集地"),
                ),
                ("collector", models.CharField(blank=True, max_length=255, verbose_name="採集者")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_collection", "所蔵中"),
                            ("on_loan", "貸出中"),
                            ("sold", "売却済み"),
                            ("disposed", "廃棄"),
                            ("lost", "紛失"),
                        ],
                        default="in_collection",
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="備考")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_specimens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["specimen_code"],
            },
        ),
        migrations.CreateModel(
            name="SpecimenEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("collection", "採集"),
                            ("purchase", "購入"),
                            ("donation", "寄贈"),
                            ("move", "移動"),
                            ("loan", "貸出"),
                            ("return", "返却"),
                            ("sale", "売却"),
                            ("disposal", "廃棄"),
                            ("loss", "紛失"),
                            ("found", "発見"),
                            ("other", "その他"),
                        ],
                        max_length=16,
                    ),
                ),
                ("occurred_on", models.DateField(default=django.utils.timezone.localdate)),
                ("note", models.TextField(blank=True, verbose_name="備考")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "specimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="specimens.specimen",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_on", "pk"],
            },
        ),
        migrations.CreateModel(
            name="SpecimenPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(max_length=500, unique=True, verbose_name="保存相対パス"),
                ),
                ("content_type", models.CharField(max_length=100, verbose_name="形式")),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "specimen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="photos",
                        to="specimens.specimen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpecimenSequence",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("next_number", models.PositiveBigIntegerField(default=1)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="specimens_sequence_singleton"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("next_number__gt", 0)),
                        name="specimens_sequence_next_number_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StorageLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名称")),
                ("note", models.TextField(blank=True, verbose_name="備考")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="specimens.storagelocation",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "pk"],
            },
        ),
        migrations.AddField(
            model_name="specimen",
            name="storage_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="specimens.storagelocation",
            ),
        ),
        migrations.CreateModel(
            name="Taxon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scientific_name",
                    models.CharField(blank=True, max_length=255, verbose_name="学名"),
                ),
                (
                    "japanese_name",
                    models.CharField(blank=True, max_length=255, verbose_name="和名"),
                ),
                ("rank", models.CharField(blank=True, max_length=64, verbose_name="分類階級")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="specimens.taxon",
                    ),
                ),
            ],
            options={
                "ordering": ["scientific_name", "japanese_name", "pk"],
            },
        ),
        migrations.AddField(
            model_name="specimen",
            name="taxon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="specimens.taxon",
            ),
        ),
        migrations.CreateModel(
            name="TaxonSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="根拠URL")),
                ("citation", models.TextField(blank=True, verbose_name="引用")),
                ("checked_on", models.DateField(blank=True, null=True, verbose_name="確認日")),
                (
                    "taxon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="specimens.taxon",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="storagelocation",
            constraint=models.UniqueConstraint(
                fields=("parent", "name"), name="specimens_storage_location_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="storagelocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("pk")), _negated=True),
                name="specimens_storage_not_own_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="taxon",
            constraint=models.CheckConstraint(
                condition=models.Q(("parent", models.F("pk")), _negated=True),
                name="specimens_taxon_not_own_parent",
            ),
        ),
    ]
