# Generated by Django 5.2.17 on 2026-10-03 08:56

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("specimens", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QRBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("requested_count", models.PositiveIntegerField(verbose_name="発行枚数")),
                ("note", models.TextField(blank=True, verbose_name="備考")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="QRLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="QR識別子",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unused", "未使用"),
                            ("assigned", "割当済み"),
                            ("retired", "無効"),
                        ],
                        default="unused",
                        max_length=16,
                    ),
                ),
                ("print_count", models.PositiveIntegerField(default=0)),
                ("last_printed_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="labels",
                        to="specimens.qrbatch",
                    ),
                ),
                (
                    "specimen",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="qr_label",
                        to="specimens.specimen",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="qrbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("requested_count__gt", 0)),
                name="specimens_qr_batch_requested_count_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="qrlabel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("specimen__isnull", True), ("status", "unused")),
                    models.Q(("specimen__isnull", False), ("status", "assigned")),
                    ("status", "retired"),
                    _connector="OR",
                ),
                name="specimens_qr_label_status_specimen_consistent",
            ),
        ),
    ]
