# Generated by Django 5.2.17 on 2026-10-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("specimens", "0002_qrbatch_qrlabel_and_more")]

    operations = [
        migrations.CreateModel(
            name="TaxonDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=255, verbose_name="データ名")),
                ("version", models.CharField(max_length=128, verbose_name="データ版")),
                ("license_name", models.CharField(max_length=128, verbose_name="ライセンス")),
                ("source_url", models.URLField(verbose_name="保存版URL")),
                ("retrieved_on", models.DateField(verbose_name="取得日")),
                ("attribution", models.TextField(verbose_name="出典表記")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["title", "version", "pk"]},
        ),
        migrations.CreateModel(
            name="TaxonDatasetRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("note", models.TextField(verbose_name="変更内容")),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="specimens.taxondataset",
                    ),
                ),
            ],
            options={"ordering": ["-imported_at", "-pk"]},
        ),
        migrations.CreateModel(
            name="TaxonDatasetRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_key", models.CharField(max_length=128, verbose_name="出典内識別子")),
                (
                    "rank",
                    models.CharField(
                        choices=[("family", "科"), ("genus", "属"), ("species", "種")],
                        max_length=16,
                        verbose_name="分類階級",
                    ),
                ),
                ("scientific_name", models.CharField(max_length=255, verbose_name="学名")),
                (
                    "japanese_name",
                    models.CharField(blank=True, max_length=255, verbose_name="和名"),
                ),
                (
                    "scientific_author",
                    models.CharField(blank=True, max_length=255, verbose_name="学名著者"),
                ),
                (
                    "original_publication_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="原記載年"
                    ),
                ),
                ("source_url", models.URLField(blank=True, verbose_name="根拠URL")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="records",
                        to="specimens.taxondataset",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="specimens.taxondatasetrecord",
                    ),
                ),
                (
                    "taxon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="specimens.taxon",
                    ),
                ),
            ],
            options={"ordering": ["rank", "scientific_name", "pk"]},
        ),
        migrations.AddConstraint(
            model_name="taxondatasetrecord",
            constraint=models.UniqueConstraint(
                fields=("dataset", "source_key"), name="specimens_taxon_dataset_record_unique_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="taxondatasetrecord",
            constraint=models.CheckConstraint(
                condition=~models.Q(("parent", models.F("pk"))),
                name="specimens_taxon_dataset_record_not_own_parent",
            ),
        ),
    ]
