# Generated by Django 5.2.17 on 2026-10-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("specimens", "0003_taxondataset_taxondatasetrecord_taxondatasetrevision"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taxondatasetrecord",
            name="rank",
            field=models.CharField(
                choices=[
                    ("kingdom", "界"),
                    ("phylum", "門"),
                    ("class", "綱"),
                    ("order", "目"),
                    ("family", "科"),
                    ("subfamily", "亜科"),
                    ("tribe", "族"),
                    ("genus", "属"),
                    ("species", "種"),
                ],
                max_length=16,
                verbose_name="分類階級",
            ),
        ),
        migrations.AlterField(
            model_name="taxondatasetrecord",
            name="scientific_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="学名"),
        ),
    ]
