# Generated by Django 5.2.17 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("accounts", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mfa_reset_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
