# Generated by Django 5.2.17 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("audit", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("admin_mfa_reset", "別管理者によるMFAリセット"),
                    ("command_mfa_reset", "サーバー管理コマンドによるMFAリセット"),
                ],
                max_length=32,
            ),
        )
    ]
