# Generated by Django 5.2.17 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("audit", "0002_command_mfa_reset_action")]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("admin_mfa_reset", "別管理者によるMFAリセット"),
                    ("command_mfa_reset", "サーバー管理コマンドによるMFAリセット"),
                    ("user_role_changed", "利用者role変更"),
                    ("user_active_state_changed", "利用者有効状態変更"),
                    ("user_created", "利用者作成"),
                    ("user_password_reissued", "利用者一時パスワード再発行"),
                ],
                max_length=32,
            ),
        )
    ]
