# Generated by Django 5.2.17 on 2026-10-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0007_alter_auditlog_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("admin_mfa_reset", "別管理者によるMFAリセット"),
                    ("command_mfa_reset", "サーバー管理コマンドによるMFAリセット"),
                    ("user_role_changed", "利用者role変更"),
                    ("user_active_state_changed", "利用者有効状態変更"),
                    ("user_created", "利用者作成"),
                    ("user_password_reissued", "利用者一時パスワード再発行"),
                    ("specimen_csv_exported", "標本CSV出力"),
                    ("qr_batch_created", "QRラベル一括発行"),
                    ("qr_batch_pdf_exported", "QRラベルPDF出力"),
                    ("qr_label_retired", "QRラベル無効化"),
                    ("storage_location_created", "保管場所作成"),
                    ("storage_location_updated", "保管場所更新"),
                    ("storage_location_deleted", "保管場所削除"),
                ],
                max_length=32,
            ),
        ),
    ]
